name: "preprocessing"
backend: "python"
max_batch_size: ${triton_max_batch_size}

input [
  {
    name: "text_input"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]

parameters {
  key: "tokenizer_dir"
  value: {
    string_value: "${tokenizer_dir}"
  }
}
instance_group [
  { 
     count: ${preprocessing_instance_count}
     kind: KIND_CPU
  }
]


